server.port: 8100

eureka:
  client.serviceUrl.defaultZone: http://192.168.1.158:8761/eureka
  instance:
    # used as search index name
    metadataMap.name: "test"
    preferIpAddress: true

management:
  server:
    port: 8101
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging.file.name: /tmp/fileservice.log

spring:
  servlet.multipart:
    max-file-size: 1000MB
    max-request-size: 1000MB

fileservice:
  path.file: /home/jie/tmp/testfileservice
  searchService: searchservice
