server.port: 8100

eureka:
  client.serviceUrl.defaultZone: http://192.168.1.158:8000/eureka
  instance:
    # used as search index name
    metadataMap.name: "test"
    preferIpAddress: true

management:
  server:
    port: 8101
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Somehow logging properties don't work. have to use logback-spring.xml.
# This property is used by logback-spring.xml
logging.file: /tmp/fileservice.log

fileservice:
  path.file: /home/jie/tmp/fileswim/file
  searchService: searchservice


