server.port: 8100

eureka:
  client.serviceUrl.defaultZone: http://gate:8000/eureka
  # must be lower case because it is used as elasticsearch index name
  instance.metadataMap.name: "one"
fileservice.path.file: /home/jie/tmp/fileswim/file
elasticsearch.host: localhost:9200
