server.port: 8100

eureka:
  client.serviceUrl.defaultZone: http://bt:8000/eureka
  instance:
    # must be lower case because it is used as elasticsearch index name
    metadataMap.name: "test"
    preferIpAddress: true

fileservice.path.file: /home/jie/tmp/fileswim/file
elasticsearch.host: localhost:9200

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    max-size: 1MB
    max-history: 10