server.port: 8100

eureka:
  client.serviceUrl.defaultZone: http://gate:8000/eureka
  instance:
    # used as search index name
    metadataMap.name: "test"
    preferIpAddress: true

fileservice:
  path.file: /home/jie/tmp/fileswim/file
  searchService: searchservice

# Somehow logging properties don't work. have to use logback-spring.xml.
# This property is used by logback-spring.xml
logging.file: /tmp/fileservice.log
